services:
  server:
    build:
      context: caddy
      dockerfile: Dockerfile

    ports:
      - "80:80"
      - "443:443"

  auth-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_JWT_KEY = ${AUTH_JWT_KEY}
      - AUTH_SERVICE_HOST = ${AUTH_SERVICE_HOST}
    networks:
      - piapp


networks:
  piapp:
    driver: bridge
